name: Report scripts

on: 
  push:
    branches:
      - 'master'
    paths:
      - '**.py'
# UTC+8 0:30, 6:30, 12:30, 20:30
  schedule:
    - cron: '30 4,12,16,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        USERNAME: ${{ secrets.Username }}
        USERCONFIG: ${{ secrets.Config }}
      run: |
        python run.py -u "$USERNAME" --config "$USERCONFIG" --daily
